In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a.shape

(2, 4)

In [4]:
a.shape = 4,2

In [5]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a.shape=2,5

In [9]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])